import { POSCustomer } from "./pos-customer-types";

export const MOCK_POS_CUSTOMERS: POSCustomer[] = [
  {
    id: "c1",
    name: "Lena Morrison",
    email: "lena.morrison@email.com",
    phone: "+1 555-0101",
    orderCount: 18,
    totalSpent: 313,
    memberSince: "Jan 2026",
  },
  {
    id: "c2",
    name: "Raj Patel",
    email: "raj.patel@email.com",
    phone: "+1 555-0102",
    orderCount: 24,
    totalSpent: 487,
    memberSince: "Feb 2026",
  },
  {
    id: "c3",
    name: "Sofia Kline",
    email: "sofia.kline@email.com",
    phone: "+1 555-0103",
    orderCount: 9,
    totalSpent: 178,
    memberSince: "Mar 2026",
  },
  {
    id: "c4",
    name: "Mark Tanner",
    email: "mark.tanner@email.com",
    phone: "+1 555-0104",
    orderCount: 6,
    totalSpent: 95,
    memberSince: "Apr 2026",
  },
  {
    id: "c5",
    name: "Anna Bergmann",
    email: "anna.bergmann@email.com",
    phone: "+1 555-0105",
    orderCount: 31,
    totalSpent: 620,
    memberSince: "Dec 2025",
  },
  {
    id: "c6",
    name: "James Wu",
    email: "james.wu@email.com",
    phone: "+1 555-0106",
    orderCount: 12,
    totalSpent: 234,
    memberSince: "Mar 2026",
  },
  {
    id: "c7",
    name: "Priya Sharma",
    email: "priya.sharma@email.com",
    phone: "+1 555-0107",
    orderCount: 8,
    totalSpent: 156,
    memberSince: "May 2026",
  },
];
