import { POSOrder } from "./pos-order-types";

export const MOCK_POS_ORDERS: POSOrder[] = [
  {
    id: "0844",
    orderNumber: "#0844",
    date: "Jun 13, 2026",
    time: "10:41 AM",
    customer: "Lena Morrison",
    table: "Table 3",
    employee: "Jamie S.",
    amount: 23.5,   // 4.50 + 3.50×2 + 12.00 = 23.50
    status: "Paid",
    tax: 1.88,
    lineItems: [
      { id: "1", name: "Cappuccino",    quantity: 1, price: 4.5,  emoji: "☕" },
      { id: "2", name: "Croissant",     quantity: 2, price: 3.5,  emoji: "🥐" },
      { id: "3", name: "Avocado Toast", quantity: 1, price: 12.0, emoji: "🥑" },
    ],
  },
  {
    id: "0843",
    orderNumber: "#0843",
    date: "Jun 13, 2026",
    time: "10:35 AM",
    customer: "Raj Patel",
    table: "Table 7",
    employee: "Priya R.",
    amount: 42.0,
    status: "Paid",
    tax: 3.36,
    lineItems: [
      { id: "1", name: "Latte", quantity: 2, price: 5.0, emoji: "☕" },
      { id: "2", name: "Club Sandwich", quantity: 1, price: 14.0, emoji: "🥪" },
      { id: "3", name: "Iced Tea", quantity: 2, price: 4.0, emoji: "🧊" },
    ],
  },
  {
    id: "0842",
    orderNumber: "#0842",
    date: "Jun 13, 2026",
    time: "10:29 AM",
    customer: "Walk-in",
    table: "Bar",
    employee: "Jamie S.",
    amount: 18.5,
    status: "Draft",
    tax: 1.48,
    lineItems: [
      { id: "1", name: "Espresso", quantity: 2, price: 3.5, emoji: "☕" },
      { id: "2", name: "Blueberry Muffin", quantity: 1, price: 4.5, emoji: "🧁" },
    ],
  },
  {
    id: "0841",
    orderNumber: "#0841",
    date: "Jun 13, 2026",
    time: "10:22 AM",
    customer: "James Wu",
    table: "Table 2",
    employee: "Marcus T.",
    amount: 31.0,
    status: "Paid",
    tax: 2.48,
    lineItems: [
      { id: "1", name: "Flat White", quantity: 1, price: 5.5, emoji: "☕" },
      { id: "2", name: "Caesar Salad", quantity: 1, price: 13.0, emoji: "🥗" },
      { id: "3", name: "Lemonade", quantity: 1, price: 4.0, emoji: "🍋" },
    ],
  },
  {
    id: "0840",
    orderNumber: "#0840",
    date: "Jun 13, 2026",
    time: "10:15 AM",
    customer: "Mark Tanner",
    table: "Table 9",
    employee: "Priya R.",
    amount: 15.5,
    status: "Cancelled",
    lineItems: [
      { id: "1", name: "Americano", quantity: 1, price: 3.5, emoji: "☕" },
      { id: "2", name: "Banana Bread", quantity: 1, price: 5.0, emoji: "🍌" },
    ],
  },
  {
    id: "0839",
    orderNumber: "#0839",
    date: "Jun 12, 2026",
    time: "9:48 PM",
    customer: "Sofia Chen",
    table: "Table 5",
    employee: "Jamie S.",
    amount: 56.0,
    status: "Paid",
    tax: 4.48,
    lineItems: [
      { id: "1", name: "Mocha", quantity: 2, price: 5.5, emoji: "☕" },
      { id: "2", name: "Steak Sandwich", quantity: 2, price: 16.0, emoji: "🥩" },
    ],
  },
  {
    id: "0838",
    orderNumber: "#0838",
    date: "Jun 12, 2026",
    time: "8:30 PM",
    customer: "Walk-in",
    table: "Bar",
    employee: "Marcus T.",
    amount: 12.0,
    status: "Draft",
    tax: 0.96,
    lineItems: [
      { id: "1", name: "Cold Brew", quantity: 2, price: 5.0, emoji: "🧊" },
    ],
  },
  {
    id: "0837",
    orderNumber: "#0837",
    date: "Jun 12, 2026",
    time: "7:15 PM",
    customer: "Elena Rossi",
    table: "Table 11",
    employee: "Priya R.",
    amount: 38.5,
    status: "Paid",
    tax: 3.08,
    lineItems: [
      { id: "1", name: "Chai Latte", quantity: 1, price: 5.0, emoji: "☕" },
      { id: "2", name: "Quiche", quantity: 1, price: 11.0, emoji: "🥧" },
      { id: "3", name: "Sparkling Water", quantity: 2, price: 3.0, emoji: "💧" },
    ],
  },
  {
    id: "0836",
    orderNumber: "#0836",
    date: "Jun 12, 2026",
    time: "6:02 PM",
    customer: "Tom Bradley",
    table: "Table 1",
    employee: "Jamie S.",
    amount: 9.5,   // 3.00 + 6.50 = 9.50
    status: "Cancelled",
    lineItems: [
      { id: "1", name: "Drip Coffee",          quantity: 1, price: 3.0, emoji: "☕" },
      { id: "2", name: "Bagel & Cream Cheese", quantity: 1, price: 6.5, emoji: "🥯" },
    ],
  },
  {
    id: "0835",
    orderNumber: "#0835",
    date: "Jun 12, 2026",
    time: "5:40 PM",
    customer: "Nina Kapoor",
    table: "Table 8",
    employee: "Marcus T.",
    amount: 47.5,
    status: "Paid",
    tax: 3.8,
    lineItems: [
      { id: "1", name: "Matcha Latte", quantity: 2, price: 6.0, emoji: "🍵" },
      { id: "2", name: "Pasta Primavera", quantity: 1, price: 16.0, emoji: "🍝" },
      { id: "3", name: "Tiramisu", quantity: 1, price: 8.0, emoji: "🍰" },
    ],
  },
];
